version: '3.8'
services:
  db-primary:
    image: postgres:latest
    container_name: postgres-primary
    hostname: pg-primary
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: manager
      POSTGRES_DB: seahawks
    volumes:
      - ./postgres-data-primary:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge