version: '3.8'
services:
  db-replica1:
    image: postgres:latest
    container_name: postgres-replica # Nome do contêiner na administração do Docker
    hostname: maresias             # Nome do servidor dentro do contêiner
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: manager
      POSTGRES_DB: db_teste
    volumes:
      - ./postgres-data-maresias:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    deploy:
      resources:
        limits:
          memory: 512M  # Limita a memória para 512MB
          cpus: "0.5"   # Limita o uso de CPU a 50%
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge